### ISSUE TITLE
Make user only be able to have one highscore in top 10

### ISSUE THREAD

**Issue by AxlLind** [AxlLind/2D-platformer#104]
Currently one user can fill up the highscore list with highscores submitted at different times.

I propose we change this by doing the following. When you first download the app we generate an ID for that person, in the same way we currently do for the highscore ID, and then use that as the node in the database:

* Highscores
  * UserID
    * That users highscore
  * UserID
    * That users highscore
  * UserID
    * That users highscore

Instead of what we have today:

* Highscores
  * ID
    * Highscore from user 1
  * ID
    * Highscore from user 2
  * ID
    * Highscore from user 1

Thoughts? Is that a good change? Cause currently if you are really good that the game and play a lot your highscores will dominate the highscore list.

**Comment by Jontpan** [comment]
Yes, I really like that. Should you be able to submit with a new name every time, or should we ask for their name once? I also think that adding your highscore to the global list should be automatic, maybe by checking the lowest highscore on the top ten and then submitting if it's higher. Doodle Jump asks if it should submit automatically, something we could think about?

We should also consider dropping firebase for google play games services.

**Comment by AxlLind** [comment]
Maybe we could save what ever name they typed in last and enter that into the input. That way you can just hit OK or change it if you want.

**Comment by Jontpan** [comment]
Yeah that would work. I think we would get a lot of things free if we tried google play services, like username? The user would have to log in to google play services though, but maybe they already are?

**Comment by Jontpan** [comment]
But firebase is lit, so.... It's definitely a hard choice....

**Comment by AxlLind** [comment]
From what I see google has no official package for google play support for unity, like what they have with firebase or google adsense. We could maybe find some third party thing but I feel like it would be easier to just stick with firebase for now.

**Comment by AxlLind** [comment]
Implemented in #105
