### ISSUE TITLE
Think about a better name

### ISSUE THREAD

**Issue by AxlLind** [AxlLind/2D-platformer#106]
'JumperGame' feels like a placeholder name. We might want to think about a better name.

**Comment by Jontpan** [comment]
Do we want it to follow the standard x-jump like the rest of these type games? It would probably make it easier to understand what it is.

Strive is a suggestion from Frida. I kinda liked it.

**Comment by AxlLind** [comment]
I think a non 'x-jump' name would be more fun.

Strive is actually quite good! 👍 I kind of like it as well

**Comment by Jontpan** [comment]
Should we just call it strive then? I haven't thought about anything better.

**Comment by AxlLind** [comment]
I kind of like the name Strive!  👍

**Comment by Jontpan** [comment]
Strive it is!
