### ISSUE TITLE
Add basic mature language filter

### ISSUE THREAD

**Issue by AxlLind** [AxlLind/2D-platformer#118]
I think maybe we want some kind of filtering of submitted user names to exclude profanity and such.

**Comment by AxlLind** [comment]
On second thought the only thing we need to maintain is the top 10 names and it would be easy enough to just change the names directly in the database. What do you think? Language filters are quite complicated and rarely work well.

**Comment by Jontpan** [comment]
Don't think our playerbase will be big enough to need this. I say if we see a name in the top 10 that is way outta line we just delete his submission.

**Comment by AxlLind** [comment]
Yeah, I'll close this
