### ISSUE TITLE
Set constraints

### ISSUE THREAD

**Issue by Jontpan** [AxlLind/2D-platformer#13]
The player should not be able to leave the screen

**Comment by AxlLind** [comment]
Tried using Mathf.Clamp on x position. Creates a magnetic field type effect at the edges. Not what we want.

Also tried to teleport the player to the other side if the exit on one side. Creates buggy effects where the player is dragged across the screen. Does not look good. Will have to find another solution.

**Comment by AxlLind** [comment]
For now solved using the first solution in the comment above. Good enough for now. Looks okay.
