### ISSUE TITLE
Improve implementation of different platforms types

### ISSUE THREAD

**Issue by AxlLind** [AxlLind/2D-platformer#31]
Currently the collision of the player with platforms is a bit hardcoded. We have a different layer for trampolines and check if we collide with that layer specifically. This won't scale well if we add more platform types.

**Comment by Jontpan** [comment]
How many platformtypes will we add which affects jumpheight? What we will probably have to do is let platforms handle player jumping, which makes sense in the trampoline case but not in the normal case. It will definitely work, but I wonder what we will gain from rewriting it? :)

**Comment by Jontpan** [comment]
also this issue is somewhat confusing as it could be improving our implementation of the game for different platforms (iOS, Android etc.)

**Comment by AxlLind** [comment]
I'm thinking for example a platform that is destroyed after you jump on it once. If we have to create layers for every platform type it might be ineffcient. Then again as you say we might not have that many platforms so this might not be an issue.

**Comment by AxlLind** [comment]
Completed in pull request #42
