### ISSUE TITLE
Using same name for high score overrides it

### ISSUE THREAD

**Issue by AxlLind** [AxlLind/2D-platformer#36]
Currently if you enter a high score with the same name as one that already exists you will override that score, meaning you can easily delete the top high score.

Currently the structure in fire base is:
* High score
  * name
    * score
  * name
    * score

and so on.

The new structure should maybe be:

* High score
  * id number
    * name
      * score
  * id number
    * name
      * score

With the id number maybe being random or based on the number currently in the DB?

**Comment by Jontpan** [comment]
Isn't this kinda what we want? it makes sense not to override in local high score but it does make sense to override in global

**Comment by AxlLind** [comment]
Well currently I can look at the top high score and simply copy that name of the number one and submit a really low score thereby deleting that high score from the list. Also there is no local high score as of now.

Since your name isn't "yours" per se anyone can just override your score

**Comment by Jontpan** [comment]
Oh, yeah. No that's bad.
