### ISSUE TITLE
Icon for the game

### ISSUE THREAD

**Issue by AxlLind** [AxlLind/2D-platformer#78]

**Comment by AxlLind** [comment]
First draft for the icon:

![icon](https://cloud.githubusercontent.com/assets/23080686/26129376/3d2dffe6-3a90-11e7-8038-e35f1b06da5d.png)

Thoughts? Any other ideas?

**Comment by Jontpan** [comment]
Looks good!

**Comment by Jontpan** [comment]
Can't think of anything spectacular, this will do the job just fine

**Comment by Jontpan** [comment]
Added in #87
